image: alpine/edge
packages:
- rust
- rustfmt
- rust-clippy
- cargo
- libelf
- zlib
sources:
- https://git.sr.ht/~loshz/syspect
environment:
  repo: syspect
tasks:
- lint: |
    cd $repo
    cargo fmt -- --check
    cargo clippy --tests -- --no-deps -D warnings
- test: |
    cd $repo
    cargo test --no-fail-fast --all-features
