image: archlinux
packages:
  - clang
  - rustup
  - libelf
  - linux-headers
  - zlib
sources:
  - https://git.sr.ht/~loshz/syspect
environment:
  repo: syspect
tasks:
  - lint: |
      cd $repo
      rustup default stable
      cargo fmt -- --check
      cargo clippy --tests -- --no-deps -D warnings
  - test: |
      cd $repo
      rustup default stable
      cargo test --no-fail-fast --all-features
