services:
  prometheus:
    image: prom/prometheus:v2.39.1
    network_mode: "host"
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.2.1
    network_mode: "host"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

