services:
  prometheus:
    image: prom/prometheus:v2.39.1
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    network_mode: "host"
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml

  grafana:
    image: grafana/grafana:9.2.1
    network_mode: "host"
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./config/grafana/dashboard.json:/var/lib/grafana/dashboards/syspect.json
      - ./config/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./config/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

