name: ci

on:
  push:
    branches:
      - main
    tags:        
      - '*'
  pull_request:
    branches:
      - main

env:
  LIBBPF_VERSION: 1.0.1

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      # Install clang and required tooling.
      - run: sudo apt update -y && sudo apt install -y clang-14 libelf-dev

      # Install libbpf.
      - run: |
          sudo mkdir -p /usr/include/bpf/
          curl -sSL "https://github.com/libbpf/libbpf/archive/refs/tags/v${{ env.LIBBPF_VERSION }}.tar.gz" -o /tmp/libbpf.tar.gz
          sudo tar -xvf /tmp/libbpf.tar.gz --strip-components=2 -C /usr/include/bpf --wildcards "libbpf-${{ env.LIBBPF_VERSION }}/src/*.h"

      # Lint code and run tests.
      - run: |
          cargo fmt -- --check
          cargo clippy --tests -- --no-deps -D warnings

      # Run all tests.
      - run: cargo test --no-fail-fast --all-features
